name: Deploy API Gateway to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          install_components: "gke-gcloud-auth-plugin"

      - name: Configure Docker
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservices-repo/api-gateway:${{ github.sha }} .
          docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservices-repo/api-gateway:${{ github.sha }}

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials music-cluster --region europe-central2 --project ${{ secrets.GCP_PROJECT_ID }}

          # Оновлюємо образ у деплойменті api-gateway-deployment
          # Важливо: назва контейнера - gateway-container
          kubectl set image deployment/api-gateway-deployment gateway-container=europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservices-repo/api-gateway:${{ github.sha }}

          # Очікування стабільного стану (щоб не було "Pending")
          kubectl rollout status deployment/api-gateway-deployment
